apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000        # Cluster port
      targetPort: 3000  # Pod container port
      nodePort: 32000   # Node port (must be between 30000-32767)
